### ISSUE TITLE
docker-compose

### ISSUE THREAD

**Issue by parhamgh2020** [htondro/realtyna-challenge#1]
To reference a container in other commands,
please specify a name for this container in the 'docker-compose.yml' file.
Naming your containers can make it easier to work with them across different parts of your project.

services:
  web:
    container_name: web 
    build:
    ...
   
  nginx:
    container_name: nginex
    ...
    
  db:
    container_name: db

**Comment by htondro** [comment]
Thank you for your guidance. The docker-compose file edited.
