### ISSUE TITLE
/reservation/available/

### ISSUE THREAD

**Issue by parhamgh2020** [htondro/realtyna-challenge#4]
TypeError at /reservation/available/
strptime() argument 1 must be str, not None

**Comment by parhamgh2020** [comment]
The POST method is not appropriate for retrieving a report.

**Comment by htondro** [comment]
As described in challenge description:

> To check if a number of rooms are available at a certain time

this endpoint is for checking available rooms at a certain time, so the certain time in `%Y-%m-%d` format should be sent to this endpoint by POST method to retrieve available rooms in that certain time.

**Comment by htondro** [comment]
Since I didn't hear from you recently, I'll close this issue.
If you like this endpoint to report available rooms in a time range, It's possible.
